version: 2
jobs:
  build:
    working_directory: ~/build-images
    docker:
      - image: docker:17.06.0-ce
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.06.0-ce
          reusable: true
      - run:
          name: build image 
          command: ./build.sh
      - run:
          name: show images
          command: docker images
      - run:
          name: release latest
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                docker login -u $DOCKER_USER -p $DOCKER_PASS
                ./release.sh
              fi
